---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml

images:
  - name: nutellinoit/eks-aws-auth-backdoor
    newTag: v0.0.1-rc0
